version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80'
      - '443:443'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    platform: linux/arm/v7
    ports:
      - '5335:5335/tcp'
      - '5335:5335/udp'
    restart: unless-stopped
    volumes:
      - './unbound:/etc/unbound'
      - '/etc/ssl/certs:/etc/ssl/certs:ro'
